// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gproto.proto

package gproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitParam struct {
	BasePath             string   `protobuf:"bytes,1,opt,name=basePath,proto3" json:"basePath,omitempty"`
	Step                 int32    `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Delete               bool     `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitParam) Reset()         { *m = InitParam{} }
func (m *InitParam) String() string { return proto.CompactTextString(m) }
func (*InitParam) ProtoMessage()    {}
func (*InitParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{0}
}

func (m *InitParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitParam.Unmarshal(m, b)
}
func (m *InitParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitParam.Marshal(b, m, deterministic)
}
func (m *InitParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitParam.Merge(m, src)
}
func (m *InitParam) XXX_Size() int {
	return xxx_messageInfo_InitParam.Size(m)
}
func (m *InitParam) XXX_DiscardUnknown() {
	xxx_messageInfo_InitParam.DiscardUnknown(m)
}

var xxx_messageInfo_InitParam proto.InternalMessageInfo

func (m *InitParam) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

func (m *InitParam) GetStep() int32 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *InitParam) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

type FileStruct struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fid                  int32    `protobuf:"varint,2,opt,name=fid,proto3" json:"fid,omitempty"`
	Mtime                int64    `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Mode                 uint32   `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileStruct) Reset()         { *m = FileStruct{} }
func (m *FileStruct) String() string { return proto.CompactTextString(m) }
func (*FileStruct) ProtoMessage()    {}
func (*FileStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{1}
}

func (m *FileStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStruct.Unmarshal(m, b)
}
func (m *FileStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStruct.Marshal(b, m, deterministic)
}
func (m *FileStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStruct.Merge(m, src)
}
func (m *FileStruct) XXX_Size() int {
	return xxx_messageInfo_FileStruct.Size(m)
}
func (m *FileStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStruct.DiscardUnknown(m)
}

var xxx_messageInfo_FileStruct proto.InternalMessageInfo

func (m *FileStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileStruct) GetFid() int32 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *FileStruct) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *FileStruct) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileStruct) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileStruct) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type DirStruct struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mtime                int64         `protobuf:"varint,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Mode                 uint32        `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	FileList             []*FileStruct `protobuf:"bytes,4,rep,name=fileList,proto3" json:"fileList,omitempty"`
	DirList              []*DirStruct  `protobuf:"bytes,5,rep,name=dirList,proto3" json:"dirList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DirStruct) Reset()         { *m = DirStruct{} }
func (m *DirStruct) String() string { return proto.CompactTextString(m) }
func (*DirStruct) ProtoMessage()    {}
func (*DirStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{2}
}

func (m *DirStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirStruct.Unmarshal(m, b)
}
func (m *DirStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirStruct.Marshal(b, m, deterministic)
}
func (m *DirStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirStruct.Merge(m, src)
}
func (m *DirStruct) XXX_Size() int {
	return xxx_messageInfo_DirStruct.Size(m)
}
func (m *DirStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_DirStruct.DiscardUnknown(m)
}

var xxx_messageInfo_DirStruct proto.InternalMessageInfo

func (m *DirStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirStruct) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *DirStruct) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *DirStruct) GetFileList() []*FileStruct {
	if m != nil {
		return m.FileList
	}
	return nil
}

func (m *DirStruct) GetDirList() []*DirStruct {
	if m != nil {
		return m.DirList
	}
	return nil
}

type SumPos struct {
	Sum                  string   `protobuf:"bytes,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Pos                  int32    `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumPos) Reset()         { *m = SumPos{} }
func (m *SumPos) String() string { return proto.CompactTextString(m) }
func (*SumPos) ProtoMessage()    {}
func (*SumPos) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{3}
}

func (m *SumPos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumPos.Unmarshal(m, b)
}
func (m *SumPos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumPos.Marshal(b, m, deterministic)
}
func (m *SumPos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumPos.Merge(m, src)
}
func (m *SumPos) XXX_Size() int {
	return xxx_messageInfo_SumPos.Size(m)
}
func (m *SumPos) XXX_DiscardUnknown() {
	xxx_messageInfo_SumPos.DiscardUnknown(m)
}

var xxx_messageInfo_SumPos proto.InternalMessageInfo

func (m *SumPos) GetSum() string {
	if m != nil {
		return m.Sum
	}
	return ""
}

func (m *SumPos) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

type SumInfo struct {
	Sum1                 uint32    `protobuf:"varint,1,opt,name=sum1,proto3" json:"sum1,omitempty"`
	Sum2List             []*SumPos `protobuf:"bytes,2,rep,name=sum2List,proto3" json:"sum2List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SumInfo) Reset()         { *m = SumInfo{} }
func (m *SumInfo) String() string { return proto.CompactTextString(m) }
func (*SumInfo) ProtoMessage()    {}
func (*SumInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{4}
}

func (m *SumInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumInfo.Unmarshal(m, b)
}
func (m *SumInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumInfo.Marshal(b, m, deterministic)
}
func (m *SumInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumInfo.Merge(m, src)
}
func (m *SumInfo) XXX_Size() int {
	return xxx_messageInfo_SumInfo.Size(m)
}
func (m *SumInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SumInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SumInfo proto.InternalMessageInfo

func (m *SumInfo) GetSum1() uint32 {
	if m != nil {
		return m.Sum1
	}
	return 0
}

func (m *SumInfo) GetSum2List() []*SumPos {
	if m != nil {
		return m.Sum2List
	}
	return nil
}

type SumList struct {
	Fid                  int32      `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	List                 []*SumInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SumList) Reset()         { *m = SumList{} }
func (m *SumList) String() string { return proto.CompactTextString(m) }
func (*SumList) ProtoMessage()    {}
func (*SumList) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{5}
}

func (m *SumList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumList.Unmarshal(m, b)
}
func (m *SumList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumList.Marshal(b, m, deterministic)
}
func (m *SumList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumList.Merge(m, src)
}
func (m *SumList) XXX_Size() int {
	return xxx_messageInfo_SumList.Size(m)
}
func (m *SumList) XXX_DiscardUnknown() {
	xxx_messageInfo_SumList.DiscardUnknown(m)
}

var xxx_messageInfo_SumList proto.InternalMessageInfo

func (m *SumList) GetFid() int32 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *SumList) GetList() []*SumInfo {
	if m != nil {
		return m.List
	}
	return nil
}

type FileSumList struct {
	List                 []*SumList `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FileSumList) Reset()         { *m = FileSumList{} }
func (m *FileSumList) String() string { return proto.CompactTextString(m) }
func (*FileSumList) ProtoMessage()    {}
func (*FileSumList) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{6}
}

func (m *FileSumList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSumList.Unmarshal(m, b)
}
func (m *FileSumList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSumList.Marshal(b, m, deterministic)
}
func (m *FileSumList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSumList.Merge(m, src)
}
func (m *FileSumList) XXX_Size() int {
	return xxx_messageInfo_FileSumList.Size(m)
}
func (m *FileSumList) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSumList.DiscardUnknown(m)
}

var xxx_messageInfo_FileSumList proto.InternalMessageInfo

func (m *FileSumList) GetList() []*SumList {
	if m != nil {
		return m.List
	}
	return nil
}

type Patch struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Pos                  int32    `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Len                  int32    `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Patch) Reset()         { *m = Patch{} }
func (m *Patch) String() string { return proto.CompactTextString(m) }
func (*Patch) ProtoMessage()    {}
func (*Patch) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{7}
}

func (m *Patch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patch.Unmarshal(m, b)
}
func (m *Patch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patch.Marshal(b, m, deterministic)
}
func (m *Patch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patch.Merge(m, src)
}
func (m *Patch) XXX_Size() int {
	return xxx_messageInfo_Patch.Size(m)
}
func (m *Patch) XXX_DiscardUnknown() {
	xxx_messageInfo_Patch.DiscardUnknown(m)
}

var xxx_messageInfo_Patch proto.InternalMessageInfo

func (m *Patch) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Patch) GetPos() int32 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func (m *Patch) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type PatchList struct {
	Fid                  int32    `protobuf:"varint,1,opt,name=fid,proto3" json:"fid,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	List                 []*Patch `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchList) Reset()         { *m = PatchList{} }
func (m *PatchList) String() string { return proto.CompactTextString(m) }
func (*PatchList) ProtoMessage()    {}
func (*PatchList) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{8}
}

func (m *PatchList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchList.Unmarshal(m, b)
}
func (m *PatchList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchList.Marshal(b, m, deterministic)
}
func (m *PatchList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchList.Merge(m, src)
}
func (m *PatchList) XXX_Size() int {
	return xxx_messageInfo_PatchList.Size(m)
}
func (m *PatchList) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchList.DiscardUnknown(m)
}

var xxx_messageInfo_PatchList proto.InternalMessageInfo

func (m *PatchList) GetFid() int32 {
	if m != nil {
		return m.Fid
	}
	return 0
}

func (m *PatchList) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *PatchList) GetList() []*Patch {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*InitParam)(nil), "gproto.InitParam")
	proto.RegisterType((*FileStruct)(nil), "gproto.file_struct")
	proto.RegisterType((*DirStruct)(nil), "gproto.dir_struct")
	proto.RegisterType((*SumPos)(nil), "gproto.SumPos")
	proto.RegisterType((*SumInfo)(nil), "gproto.SumInfo")
	proto.RegisterType((*SumList)(nil), "gproto.SumList")
	proto.RegisterType((*FileSumList)(nil), "gproto.FileSumList")
	proto.RegisterType((*Patch)(nil), "gproto.Patch")
	proto.RegisterType((*PatchList)(nil), "gproto.PatchList")
}

func init() { proto.RegisterFile("gproto.proto", fileDescriptor_983ff0cd6c838bbe) }

var fileDescriptor_983ff0cd6c838bbe = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x95, 0xf3, 0xb5, 0xe9, 0x74, 0x0b, 0xc8, 0x20, 0x14, 0x71, 0x0a, 0xe6, 0x12, 0xa1, 0xd5,
	0x22, 0xca, 0x0f, 0x80, 0x13, 0x52, 0x25, 0x0e, 0x91, 0xcb, 0x1d, 0x79, 0x37, 0x2e, 0xb5, 0x14,
	0x27, 0x51, 0xec, 0x5c, 0xb8, 0xf3, 0x63, 0xf8, 0x97, 0xc8, 0x13, 0x3b, 0xa9, 0x54, 0xd8, 0x4b,
	0xf4, 0x66, 0xf2, 0xe6, 0xbd, 0xe7, 0xb1, 0xe1, 0xf6, 0xe7, 0x30, 0xf6, 0xb6, 0xbf, 0xc7, 0x2f,
	0xcd, 0xe6, 0x8a, 0x1d, 0x61, 0x73, 0xe8, 0x94, 0xad, 0xc5, 0x28, 0x34, 0x7d, 0x03, 0xf9, 0x83,
	0x30, 0xb2, 0x16, 0xf6, 0x5c, 0x90, 0x92, 0x54, 0x1b, 0xbe, 0xd4, 0x94, 0x42, 0x62, 0xac, 0x1c,
	0x8a, 0xa8, 0x24, 0x55, 0xca, 0x11, 0xd3, 0xd7, 0x90, 0x35, 0xb2, 0x95, 0x56, 0x16, 0x71, 0x49,
	0xaa, 0x9c, 0xfb, 0x8a, 0xfd, 0x26, 0xb0, 0x3d, 0xa9, 0x56, 0xfe, 0x30, 0x76, 0x9c, 0x1e, 0xad,
	0x9b, 0xed, 0x84, 0x96, 0x5e, 0x13, 0x31, 0x7d, 0x01, 0xf1, 0x49, 0x35, 0x5e, 0xce, 0x41, 0xfa,
	0x0a, 0x52, 0x6d, 0x95, 0x9e, 0xc5, 0x62, 0x3e, 0x17, 0x6e, 0x56, 0xf7, 0x8d, 0x2c, 0x92, 0x92,
	0x54, 0x3b, 0x8e, 0x18, 0xb3, 0xa8, 0x5f, 0xb2, 0x48, 0x91, 0x88, 0xd8, 0xf5, 0xce, 0xc2, 0x9c,
	0x8b, 0x6c, 0xf6, 0x70, 0x98, 0xfd, 0x21, 0x00, 0x8d, 0x1a, 0x9f, 0x8a, 0xb1, 0x98, 0x46, 0xff,
	0x32, 0x8d, 0x2f, 0x4c, 0x3f, 0x40, 0xee, 0xce, 0xf4, 0x4d, 0x19, 0x5b, 0x24, 0x65, 0x5c, 0x6d,
	0xf7, 0x2f, 0xef, 0xfd, 0x4a, 0x2f, 0xce, 0xca, 0x17, 0x12, 0xbd, 0x83, 0x9b, 0x46, 0x8d, 0xc8,
	0x4f, 0x91, 0x4f, 0x03, 0x7f, 0xcd, 0xc4, 0x03, 0x85, 0xdd, 0x41, 0x76, 0x9c, 0x74, 0xdd, 0x1b,
	0xb7, 0x19, 0x33, 0x69, 0x9f, 0xd2, 0x41, 0xd7, 0x19, 0x7a, 0x13, 0x76, 0x35, 0xf4, 0x86, 0x1d,
	0xe0, 0xe6, 0x38, 0xe9, 0x43, 0x77, 0xea, 0x71, 0x19, 0x93, 0xfe, 0x88, 0xfc, 0x1d, 0x47, 0x4c,
	0xdf, 0x43, 0x6e, 0x26, 0xbd, 0x47, 0xef, 0x08, 0xbd, 0x9f, 0x05, 0xef, 0xd9, 0x84, 0x2f, 0xff,
	0xd9, 0x17, 0x94, 0xc2, 0xc4, 0xfe, 0x4e, 0xc8, 0x7a, 0x27, 0xef, 0x20, 0x69, 0x57, 0x91, 0xe7,
	0x17, 0x22, 0xce, 0x9b, 0xe3, 0x4f, 0xb6, 0x87, 0xed, 0x57, 0xd5, 0xca, 0xa0, 0x12, 0x66, 0xc8,
	0xd5, 0x8c, 0xfb, 0xed, 0x67, 0x3e, 0x43, 0x5a, 0x0b, 0xfb, 0x88, 0xef, 0xaa, 0x11, 0x56, 0xa0,
	0xe9, 0x2d, 0x47, 0x7c, 0x7d, 0x5e, 0xd7, 0x69, 0x65, 0x87, 0xf7, 0x91, 0x72, 0x07, 0xd9, 0x77,
	0xd8, 0xa0, 0xc0, 0x7f, 0x82, 0x87, 0xe7, 0x10, 0xad, 0xcf, 0x81, 0xbe, 0xf5, 0xc1, 0x62, 0x0c,
	0xb6, 0x0b, 0xc1, 0x50, 0x66, 0x8e, 0xf5, 0x90, 0x61, 0xeb, 0xd3, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x24, 0x01, 0x5d, 0x02, 0x2d, 0x03, 0x00, 0x00,
}
