// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gproto.proto

package gproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileStruct struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mtime                int64    `protobuf:"varint,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileStruct) Reset()         { *m = FileStruct{} }
func (m *FileStruct) String() string { return proto.CompactTextString(m) }
func (*FileStruct) ProtoMessage()    {}
func (*FileStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{0}
}

func (m *FileStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileStruct.Unmarshal(m, b)
}
func (m *FileStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileStruct.Marshal(b, m, deterministic)
}
func (m *FileStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileStruct.Merge(m, src)
}
func (m *FileStruct) XXX_Size() int {
	return xxx_messageInfo_FileStruct.Size(m)
}
func (m *FileStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_FileStruct.DiscardUnknown(m)
}

var xxx_messageInfo_FileStruct proto.InternalMessageInfo

func (m *FileStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileStruct) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *FileStruct) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileStruct) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileStruct) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type DirStruct struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mtime                int64         `protobuf:"varint,2,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Mode                 uint32        `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	FileList             []*FileStruct `protobuf:"bytes,4,rep,name=fileList,proto3" json:"fileList,omitempty"`
	DirList              []*DirStruct  `protobuf:"bytes,5,rep,name=dirList,proto3" json:"dirList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DirStruct) Reset()         { *m = DirStruct{} }
func (m *DirStruct) String() string { return proto.CompactTextString(m) }
func (*DirStruct) ProtoMessage()    {}
func (*DirStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_983ff0cd6c838bbe, []int{1}
}

func (m *DirStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirStruct.Unmarshal(m, b)
}
func (m *DirStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirStruct.Marshal(b, m, deterministic)
}
func (m *DirStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirStruct.Merge(m, src)
}
func (m *DirStruct) XXX_Size() int {
	return xxx_messageInfo_DirStruct.Size(m)
}
func (m *DirStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_DirStruct.DiscardUnknown(m)
}

var xxx_messageInfo_DirStruct proto.InternalMessageInfo

func (m *DirStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DirStruct) GetMtime() int64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

func (m *DirStruct) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *DirStruct) GetFileList() []*FileStruct {
	if m != nil {
		return m.FileList
	}
	return nil
}

func (m *DirStruct) GetDirList() []*DirStruct {
	if m != nil {
		return m.DirList
	}
	return nil
}

func init() {
	proto.RegisterType((*FileStruct)(nil), "gproto.file_struct")
	proto.RegisterType((*DirStruct)(nil), "gproto.dir_struct")
}

func init() { proto.RegisterFile("gproto.proto", fileDescriptor_983ff0cd6c838bbe) }

var fileDescriptor_983ff0cd6c838bbe = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0x6c, 0x10, 0x9e, 0x52, 0x31, 0x17, 0x77, 0x5a, 0x66, 0x4e,
	0x6a, 0x7c, 0x71, 0x49, 0x51, 0x69, 0x72, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x24, 0xc2, 0xc5, 0x9a, 0x5b, 0x92, 0x99,
	0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0xe1, 0x80, 0x54, 0xe6, 0xe6, 0xa7, 0xa4,
	0x4a, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0xe2, 0xcc, 0xaa, 0x54, 0x09,
	0x16, 0xb0, 0x42, 0x30, 0x1b, 0x24, 0x96, 0x91, 0x58, 0x9c, 0x21, 0xc1, 0x0a, 0x31, 0x11, 0xc4,
	0x56, 0x5a, 0xc9, 0xc8, 0xc5, 0x95, 0x92, 0x59, 0x44, 0x1d, 0x4b, 0xf5, 0xb9, 0x38, 0x40, 0x3e,
	0xf0, 0xc9, 0x2c, 0x2e, 0x91, 0x60, 0x51, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd6, 0x83, 0x7a, 0x15,
	0xc9, 0x67, 0x41, 0x70, 0x45, 0x42, 0x3a, 0x5c, 0xec, 0x29, 0x99, 0x45, 0x60, 0xf5, 0xac, 0x60,
	0xf5, 0x42, 0x30, 0xf5, 0x08, 0x37, 0x05, 0xc1, 0x94, 0x24, 0xb1, 0x81, 0xa5, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x68, 0xe2, 0x7d, 0x17, 0x3f, 0x01, 0x00, 0x00,
}
